### ISSUE TITLE
Google 镜像站搜集(2016年7月3日更新)

### ISSUE THREAD

**Issue by xiaoyu2er** [xiaoyu2er/blog#2]
自由的接触信息应该是每个人不可剥夺的基本权利.

每周更新! 

敬请关注! [google-mirror-check npm包已发布](https://github.com/xiaoyu2er/google-mirror-check)

如果您是以下镜像的作者, 且不希望出现在以下列表中，可以联系[我](mailto:zongyanqi@foxmail.com)移除链接。
- [http://google.hcs.world/](http://google.hcs.world/) (3836ms)
- [http://soguge.com/](http://soguge.com/) (3839ms)
- [http://ssdao.cdjltz.com/](http://ssdao.cdjltz.com/) (9751ms)

**Comment by ityan2008** [comment]
试一下这个学术搜索，挺全面，很方便  http://so.sciencesoft.cn/
